#!/bin/bash

source /etc/environment

# default 1 executor 
jenkins_slave_executors=${jenkins_slave_executors:-2}
jenkins_root_directory=${jenkins_root_directory:-/users/ubuntu/jenkins_data}
jenkins_slave_description=${jenkins_slave_description:-echo-win-build}
jenkins_slave_labels=${jenkins_slave_labels:-echo-build}
jenkins_master_ip=${jenkins_master_ip:-echo-jenkins.test.logicnow.us:8080}
jenkins_slave_name="echo-win-build"
jenkins_slave_auth_username="pct-build"
# jenkins_slave_auth_password=${jenkins_slave_auth_password}

# this is specific for aws, grabbing the private network interface (second in the list)
hostname=`ifconfig | awk '/inet addr/{print substr($2,6)}' | tail -n2 | head -n1`

# optional login for jenkins account
if [ -n "${jenkins_slave_auth_username}" ] && [ -n "${jenkins_slave_auth_password}" ]; then
  auth_string="$jenkins_slave_auth_username:$jenkins_slave_auth_password@"
else
  auth_string=""
fi

build_host="http://${auth_string}${jenkins_master_ip}"

registration_full_url="$build_host/plugin/dynaslave/createSlave?name=$jenkins_slave_name&executors=$jenkins_slave_executors&remoteFsRoot=$jenkins_root_directory&description=$jenkins_slave_description&labels=$jenkins_slave_labels&hostname=$hostname"

echo $registration_full_url
curl -f --silent ${buildhost}/computer/${jenkins_slave_name}
ret=$?
if [ ${ret} -ne 0 ]
then
    echo "Jenkins registration lost, re-registering"
    curl -f --silent ${registration_full_url}
    ret=$?
    if [ ${ret} -eq 0 ]
    then
        echo "Registration with Jenkins successful"
    else
        echo "Registration with jenkins FAILED"
    fi
fi
