#!/bin/bash

jenkins_slave_auth_username="pct-build"
jenkins_slave_auth_password=$1
jenkins_root_directory="/c/jenkins-slave'
jenkins_slave_prefix="dynaslave"
jenkins_master_ip=10.21.0.11:8080
jenkins_slave_name="echo-win-build"
jenkins_slave_prefix="dynaslave"

# optional login for jenkins account
if [ -n "${jenkins_slave_auth_username}" ] && [ -n "${jenkins_slave_auth_password}" ]; then
  auth_string="$jenkins_slave_auth_username:$jenkins_slave_auth_password@"
  JNLP_AUTH=" -jnlpCredentials $jenkins_slave_auth_username:$jenkins_slave_auth_password"
else
  auth_string=""
  JNLP_AUTH=""
fi

BUILDS_HOME=${jenkins_root_directory}
BUILDS_URL=http://${auth_string}${jenkins_master_ip}
# Change the HOST prefix from ds- if you set it to something different in the Jenkins system config.
HOST=${jenkins_slave_prefix}-${jenkins_slave_name}
LOG=${BUILDS_HOME}/log
SLAVE_TOOLS=${BUILDS_HOME}/scripts
SLAVE_JAR=${BUILDS_URL}/jnlpJars/slave.jar
JNLP_URL="${BUILDS_URL}/computer/${HOST}/slave-agent.jnlp"

# java must be installed already

refresh_slave_jar() {
    pushd ${SLAVE_TOOLS}
    curl -O ${SLAVE_JAR}
    popd
}

launch_slave() {
    pkill -f slave.jar
    nohup java -jar ${SLAVE_TOOLS}/slave.jar \
      -jnlpUrl ${JNLP_URL} ${JNLP_AUTH} > ${LOG} 2>&1 &
    echo Slave started as process $$
}

main() {
    [[ -d ${BUILDS_HOME}/slave ]] && mkdir -p ${BUILDS_HOME}/slave
    refresh_slave_jar
    launch_slave
}

main
